image: registry.gitlab.com/evernym/containers/build-verity:0f2dbf8d

variables:
  MASTER_PROJECT_ID: "327"
  indyNodeVersion: "1.12.3"
  sovtokenVersion: "1.0.8"
  TRIGGERAPI_URL_VERITY_RELEASE: "https://gitlab.corp.evernym.com/api/v4/projects/688/trigger/pipeline"
  # TRIGGERAPI_REF_VERITY_RELEASE: "auto-deploy"

stages:
  - check
  - test
  - package
  - publish
  - deploy

include:
  - '/cicd/jobs/check.yml'
  - '/cicd/jobs/test.yml'
  - '/cicd/jobs/package.yml'
  - '/cicd/jobs/publish.yml'
  - '/cicd/jobs/deploy.yml'
  
