apiVersion: v1
kind: ConfigMap
metadata:
  name: vars-dev-cas
  labels:
    tags.datadoghq.com/service: {{ .Values.service }}
    tags.datadoghq.com/env: {{ .Values.env }}
data:
{{ toYaml .Values.vars | indent 2 }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: file-dev-cas
  labels:
    tags.datadoghq.com/service: {{ .Values.service }}
    tags.datadoghq.com/env: {{ .Values.env }}
data:
{{- tpl ((.Files.Glob "assets/*").AsConfig) . | nindent 2 }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: ledger-genesis-dev-cas
  labels:
    tags.datadoghq.com/service: {{ .Values.service }}
    tags.datadoghq.com/env: {{ .Values.env }}
data:
{{- tpl ((.Files.Glob "assets/genesis.txt").AsConfig) . | nindent 2 }}
