apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "verity.fullname" . }}
  annotations:
    app.gitlab.com/app: {{ .Values.gitlab_ci_project_path_slug }}
    app.gitlab.com/env: {{ .Values.env }}
spec:
  #strategy:
  #  type: "Recreate"
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: {{ template "verity.fullname" . }}
  replicas: {{ .Values.startReplicas }}
  template:
    metadata:
      labels:
        app: {{ template "verity.fullname" . }}
        actorSystemName: verity
      annotations:
        app.gitlab.com/app: {{ .Values.gitlab_ci_project_path_slug }}
        app.gitlab.com/env: {{ .Values.env }}
        {{- if .Values.deployment.vault.enable }}
        vault.hashicorp.com/agent-inject: "true"
        vault.hashicorp.com/role: "k8s-eks-{{ .Values.env }}"
        vault.hashicorp.com/auth-path: "auth/k8s/eks-{{ .Values.gitlab_env }}"
        vault.hashicorp.com/agent-inject-secret-credentials: "kubernetes_secrets/eks-{{ .Values.gitlab_env }}/{{ .Values.name }}-{{ .Values.service }}"
        vault.hashicorp.com/tls-secret: vault-tls-secret
        vault.hashicorp.com/ca-cert: /vault/tls/evernym-root-ca.crt
        vault.hashicorp.com/agent-pre-populate-only : "true"
        vault.hashicorp.com/agent-inject-template-credentials: |
          {{`{{ with secret `}}"kubernetes_secrets/eks-{{ .Values.gitlab_env }}/{{ .Values.name }}-{{ .Values.service }}"{{` -}}`}}
          {{`{{ range $k, $v := .Data.data -}}
            export {{ $k }}={{ $v }}
          {{ end }}
          {{- end }}`}}
        {{- end }}
    spec:
      containers:
      - name: {{ template "verity.fullname" . }}
        image: {{ .Values.deployment.image }}:{{ .Values.deployment.tag }}
        resources:
          requests:
            memory: {{ .Values.deployment.resources.requests.memory }}
            cpu: {{ .Values.deployment.resources.requests.cpu }}
          limits:
            memory: {{ .Values.deployment.resources.limits.memory }}
            cpu: {{ .Values.deployment.resources.limits.cpu }}
        startupProbe:
          httpGet:
            path: /agency/heartbeat
            port: 9000
          periodSeconds: 10
          failureThreshold: 20
        readinessProbe:
          httpGet:
            path: /agency
            port: 9000
        livenessProbe:
          httpGet:
            path: /agency/heartbeat
            port: 9000
          periodSeconds: 30
          failureThreshold: 1
        envFrom:
        - configMapRef:
            name: vars-{{ template "verity.fullname" . }}
        env:
        - name: CINNAMON__CHMETRICS__DATADOG_REPORTER__HOST
          valueFrom:
            fieldRef:
              fieldPath: status.hostIP
        volumeMounts:
        - name: config-files
          mountPath: /etc/verity/verity-application/config-map
          readOnly: true
        - name: ledger-genesis-files
          mountPath: /var/lib/indy/
          readOnly: true
        ports:
        - name: http
          containerPort: {{ .Values.deployment.containerPort }}
        - name: management
          containerPort: 8558
          protocol: TCP
        imagePullPolicy: {{ .Values.deployment.imagePullPolicy }}
      volumes:
      - name: config-files
        configMap:
          name: file-{{ template "verity.fullname" . }}
      - name: ledger-genesis-files
        configMap:
          name: ledger-genesis-{{ template "verity.fullname" . }}

