kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ template "verity.fullname" . }}
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "watch", "list"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ template "verity.fullname" . }}
subjects:
- kind: User
  name: system:serviceaccount:default:{{ template "verity.serviceAccountName" . }}
roleRef:
  kind: Role
  name: {{ template "verity.fullname" . }}
  apiGroup: rbac.authorization.k8s.io
