apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: aws-secrets-{{ template "verity.fullname" . }}
spec:
  provider: aws
  parameters:
    objects: |
        - objectName: {{ required ".Values.secrets.awsSecretsNameCredentialsTf is required" .Values.secrets.awsSecretsNameCredentialsTf | quote }}
          objectType: "secretsmanager"
          objectAlias: "credentials-tf.json"
        - objectName: {{ required ".Values.secrets.awsSecretsNameCredentials is required" .Values.secrets.awsSecretsNameCredentials | quote }}
          objectType: "secretsmanager"
          objectAlias: "credentials.json"
