apiVersion: v1
kind: Service
metadata:
  name: {{ template "verity.fullname" . }}
spec:
  type: {{ .Values.k8sService.type }}
  selector:
    {{- include "verity.selectorLabels" . | nindent 4 }}
  ports:
    - port: {{ .Values.k8sService.port }}
      targetPort: {{ .Values.k8sService.targetPort }}
