apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "verity.serviceAccountName" . }}
  annotations:
    eks.amazonaws.com/role-arn: {{ required ".Values.secretsRoleArn is required" .Values.secretsRoleArn }}
