apiVersion: v1
kind: Service
metadata:
  name: {{ template "verity.fullname" . }}
  labels:
    tags.datadoghq.com/service: {{ .Values.service }}
    tags.datadoghq.com/environment: {{ .Values.env }}
spec:
  type: {{ .Values.k8sService.type }}
  selector:
    app: {{ template "verity.fullname" . }}
  ports:
    - port: {{ .Values.k8sService.port }}
      targetPort: {{ .Values.k8sService.targetPort }}

