apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service }}-{{ .Values.name }}-{{ .Values.env }}
spec:
  type: {{ .Values.k8sService.type }}
  selector:
    app: {{ .Values.service }}-{{ .Values.name }}-{{ .Values.env }}
  ports:
    - port: {{ .Values.k8sService.port }}
      targetPort: {{ .Values.k8sService.targetPort }}

