apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.deployment.name }}
spec:
  type: {{ .Values.k8sService.type }}
  selector:
    app: {{ .Values.deployment.name }}
  ports:
    - port: {{ .Values.k8sService.port }}
      targetPort: {{ .Values.k8sService.targetPort }}