apiVersion: apps/v1
kind: Deployment
metadata:
  name: indy-pool
spec:
  replicas: 1
  selector:
    matchLabels:
      app: indy-pool
  template:
    metadata:
      labels:
        app: indy-pool
    spec:
      containers:
      - name: indy-pool
        image: registry.gitlab.com/evernym/containers/indy-pool:1.12.4_1.0.9
        resources:
          requests:
            memory: 256Mi
            cpu: 250m
          limits:
            memory: 512Mi
            cpu: 500m
        imagePullPolicy: IfNotPresent
        ports:
          - containerPort: 9701
          - containerPort: 9702
          - containerPort: 9703
          - containerPort: 9704
          - containerPort: 9705
          - containerPort: 9706
          - containerPort: 9707
          - containerPort: 9708
          - containerPort: 5678
          - containerPort: 5679
        args:
          - "--TAA_ENABLED=false"