deployment:
  name: "iac-cas"
  image: "609723053065.dkr.ecr.ap-southeast-1.amazonaws.com/iac-verity-cas"
  tag: "veritymainplusconf"
  imagePullPolicy: "Always"
  containerPort: 9000
  vault:
    enable: false
  terminationGracePeriodSeconds: 120
  probes:
    startup:
      path: "/verity/node/liveness"
      periodSeconds: 10
      timeoutSeconds: 2
      failureThreshold: 20
    readiness:
      path: "/verity/node/readiness"
      periodSeconds: 5
      timeoutSeconds: 2
      failureThreshold: 1
    liveness:
      path: "/verity/node/liveness"
      periodSeconds: 5
      timeoutSeconds: 2
      failureThreshold: 2
k8sService:
  type: NodePort
  port: 80
  targetPort: 9000
ingress:
  # force_ssl: false
  # healthcheckPath: "/verity/node/readiness"
  # healthcheckIntervalSeconds: 5
  # healthcheckTimeoutSeconds: 2
  # unhealthyThresholdCount: 2
  # deregistrationDelay: 120
  targetGroupARNarn: "arn:aws:elasticloadbalancing:ap-southeast-1:609723053065:targetgroup/iac-cas/bf2b04271c90f846" #TODO: make external
serviceAccount:
  name: "kubernetes-external-secrets"
  arn: "arn:aws:iam::609723053065:role/iac-external-secrets" #TODO: make external
secrets:
  awsSecretsNameCredentialsTf: "iac/app/cas/credentials-tf" #TODO: make external
# List of sponsors for Verity
sponsors:
# List configuration for TAA.
taa:
# VDR configuration
vdr:
# Custom and Adhoc Configuration for Verity in HOCON Notation
# Intended to allow quick injection of config that is
# not managed by this helm chart
customConfig: |
