deployment:
  image: "609723053065.dkr.ecr.ap-southeast-1.amazonaws.com/dev-cas" # FIXME non-prefixed image for both cas and vas
  tag: "latest"
  imagePullPolicy: "IfNotPresent" # TODO legacy Always
  containerPort: 9001 # TODO legacy 9000
  vault:
    enable: false
  terminationGracePeriodSeconds: 120
  probes:
    startup:
      path: "/verity/node/liveness"
      periodSeconds: 10
      timeoutSeconds: 2
      failureThreshold: 20
    readiness:
      path: "/verity/node/readiness"
      periodSeconds: 5
      timeoutSeconds: 2
      failureThreshold: 1
    liveness:
      path: "/verity/node/liveness"
      periodSeconds: 5
      timeoutSeconds: 2
      failureThreshold: 2
  useAffinity: false # TODO requires better configuraton
k8sService:
  type: NodePort
  port: 80
  targetPort: 9001 # TODO legacy 9000
ingress:
  enabled: false
  force_ssl: false
  healthcheckPath: "/verity/node/readiness"
  healthcheckIntervalSeconds: 5
  healthcheckTimeoutSeconds: 2
  unhealthyThresholdCount: 2
  deregistrationDelay: 120
  # targetGroupARNarn: "arn:aws:elasticloadbalancing:ap-southeast-1:609723053065:targetgroup/iac-cas/bf2b04271c90f846" #TODO: make external
  targetGroupARNarn: ""
serviceAccount:
  name: "kubernetes-external-secrets"
  # arn: "arn:aws:iam::609723053065:role/iac-external-secrets" #TODO: make external
  arn: ""
secrets:
  # awsSecretsNameCredentialsTf: "iac/app/cas/credentials-tf" #TODO: make external
  awsSecretsNameCredentialsTf: ""

# TODO don't we need sponsors, taa, vdr ???
# List of sponsors for Verity
#sponsors:
# List configuration for TAA.
#taa:
# VDR configuration
#vdr:

vars: {} # TODO not declared in legacy

# Custom and Adhoc Configuration for Verity in HOCON Notation
# Intended to allow quick injection of config that is
# not managed by this helm chart
customConfig: |
