deployment:
  image: "609723053065.dkr.ecr.ap-southeast-1.amazonaws.com/dev-cas"
  tag: "latest"
  imagePullPolicy: "Always"
  containerPort: 9000
  vault:
    enable: true
  terminationGracePeriodSeconds: 120
  probes:
    startup:
      path: "/verity/node/liveness"
      periodSeconds: 10
      timeoutSeconds: 2
      failureThreshold: 20
    readiness:
      path: "/verity/node/readiness"
      periodSeconds: 5
      timeoutSeconds: 2
      failureThreshold: 1
    liveness:
      path: "/verity/node/liveness"
      periodSeconds: 5
      timeoutSeconds: 2
      failureThreshold: 2
k8sService:
  type: NodePort
  port: 80
  targetPort: 9000
ingress:
  force_ssl: false
  healthcheckPath: "/verity/node/readiness"
  healthcheckIntervalSeconds: 5
  healthcheckTimeoutSeconds: 2
  unhealthyThresholdCount: 2
  deregistrationDelay: 120
# ENV
vars:
  VERITY_HTTP_PORT: "9000"
  VERITY_AKKA_REMOTE_PORT: "2850"
  VERITY_AKKA_MANAGEMENT_HTTP_PORT: "8850"
  VERITY_KAMON_STATE_PAGE_PORT: "5850"
  VERITY_KAMON_ENVIRONMENT_SERVICE: "CAS_1"
  VERITY_KAMON_PROMETHEUS_PORT: "6800"
  VERITY_BASIC_EVENT_STORE_PORT: "7800"
  VERITY_BASIC_EVENT_CONSUMER_PORT: "8800"
  VERITY_DYNAMODB_JOURNAL_TABLE: "agency_akka_cas"
  VERITY_DYNAMODB_SNAPSHOT_TABLE: "agency_akka_snapshot_cas"
  TAA_ENABLE: "false"
  LIB_INDY_LEDGER_TAA_ENABLED: "false"
  GENESIS_TXN_FILE_LOCATION: "/etc/verity/verity-application/genesis.txt"

# List of customers of Verity
customers:
  path: /assets/customers.conf
# List of sponsors for Verity
sponsors:
  path: /assets/sponsors.conf
# Push notification config
push_notif:
  path: /assets/push-notif.conf
# Metrics
metrics:
  path: /assets/metrics.conf
# Usage rules
usage_rules:
  path: /assets/usage-rules.conf
# SMS preferred orders
sms_preferred_order:
  path: /assets/sms-preferred-order.conf
# Allowed IPs
allowed_ips:
  path: /assets/internal-api-allowed-ips.conf
# logback configuration
logback:
  path: /assets/logback.xml
# VDR configuration
vdr:
  path: /assets/vdr.conf
# Genesis file
ledger_genesis:
  path: /assets/genesis.txt
# Custom and Adhoc Configuration for Verity in HOCON Notation
# Intended to allow quick injection of config that is
# not managed by this helm chart
customConfig: |
