## This will override the default app.kubernetes.io/instance label for all Objects.
# instanceLabelOverride: verity

deployment:
  service:
  env:
  image: "609723053065.dkr.ecr.ap-southeast-1.amazonaws.com/verity"
  tag: "latest" # FIXME use versioned one
  imagePullPolicy: "Always" # FIXME use IfNotPresent once versioned tag is set
  containerPort: 9000
  vault:
    enable: false
  terminationGracePeriodSeconds: 120
  probes:
    startup:
      path: "/verity/node/liveness"
      periodSeconds: 10
      timeoutSeconds: 2
      failureThreshold: 20
    readiness:
      path: "/verity/node/readiness"
      periodSeconds: 5
      timeoutSeconds: 2
      failureThreshold: 1
    liveness:
      path: "/verity/node/liveness"
      periodSeconds: 5
      timeoutSeconds: 2
      failureThreshold: 2
  resources: # TODO tune the values
    requests:
      memory: 768Mi
      cpu: 250m
    limits:
      memory: 1024Mi
      cpu: 1000m
  useAffinity: false # TODO requires better configuraton
k8sService:
  type: NodePort
  port: 80
  targetPort: 9000
ingress:
  # if empty internal ingress configuration is used
  targetGroupARNarn: ""
  # internal ingress configuration
  force_ssl: false
  healthcheckPath: "/verity/node/readiness"
  healthcheckIntervalSeconds: 5
  healthcheckTimeoutSeconds: 2
  unhealthyThresholdCount: 2
  deregistrationDelay: 120

# role arn to use for EKS service account
secretsRoleArn: ""

secrets:
  # name/alias of the secret in AWS SecretsManager to put into credentials-tf.json
  awsSecretsNameCredentialsTf: ""

# TODO don't we need sponsors, taa, vdr ???
# List of sponsors for Verity
#sponsors:
# List configuration for TAA.
#taa:
# VDR configuration
#vdr:

# application configuraion variables
vars: {}

# Custom and Adhoc Configuration for Verity in HOCON Notation
# Intended to allow quick injection of config that is
# not managed by this helm chart
customConfig: |
