## This will override the default app.kubernetes.io/instance label for all Objects.
# instanceLabelOverride: verity

deployment:
  image: "609723053065.dkr.ecr.ap-southeast-1.amazonaws.com/verity"
  tag: "0.0.1"
  imagePullPolicy: "IfNotPresent"
  containerPort: 9000
  terminationGracePeriodSeconds: 120
  probes:
    startup:
      path: "/verity/node/liveness"
      periodSeconds: 10
      timeoutSeconds: 2
      failureThreshold: 20
    readiness:
      path: "/verity/node/readiness"
      periodSeconds: 5
      timeoutSeconds: 2
      failureThreshold: 1
    liveness:
      path: "/verity/node/liveness"
      periodSeconds: 5
      timeoutSeconds: 2
      failureThreshold: 2

k8sService:
  type: NodePort
  port: 80
  targetPort: 9000

ingress:
  # if empty - internal ingress is used
  targetGroupARNarn: ""
  # internal ingress configuration
  force_ssl: false
  healthcheckPath: "/verity/node/readiness"
  healthcheckIntervalSeconds: 5
  healthcheckTimeoutSeconds: 2
  unhealthyThresholdCount: 2
  deregistrationDelay: 120

# REQUIRED
# role arn to use for EKS service account
secretsRoleArn: ""

secrets:
  # REQUIRED
  # name/alias of the secret in AWS SecretsManager to put into credentials-tf.json
  awsSecretsNameCredentialsTf: ""

  # REQUIRED
  # name/alias of the secret in AWS SecretsManager to put into credentials.json
  awsSecretsNameCredentials: ""

# List of sponsors for Verity
sponsors:
# List configuration for TAA.
taa:
# VDR configuration
vdr:

# application configuraion variables
vars: {}

# Custom and Adhoc Configuration for Verity in HOCON Notation
# Intended to allow quick injection of config that is
# not managed by this helm chart
customConfig: |
